version: '3'
services:
  app:
    build:
      context: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/cafedotcom
      - public-data:/cafedotcom/public
      - tmp-data:/cafedotcom/tmp
      - log-data:/cafedotcom/log
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
  pgweb:
    image: donnex/pgweb
    command: -s --bind=0.0.0.0 --listen=8080 --url postgresql://postgres:postgres@db/cafedotcom_development?sslmode=disable
    links:
      - db:db
    ports:
      - '8080:8080'
  web:
    build:
      context: ./nginx
    volumes:
      - public-data:/cafedotcom/public
      - tmp-data:/cafedotcom/tmp
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:
