version: '3'
services:
  app:
    build:
      context: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/cafedotcom
      - public-data:/cafedotcom/public
      - tmp-data:/cafedotcom/tmp
      - log-data:/cafedotcom/log
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - db-data:/var/run/postgresql
  web:
    build:
      context: ./nginx
    volumes:
      - public-data:/cafedotcom/public
      - tmp-data:/cafedotcom/tmp
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:
