version: '2'
services:
  web:
    build: .
    image: web_multicontainer
    volumes:
      - /app/log # persist logs
    depends_on:
      - db

  nginx:
    build: containers/nginx
    ports:
      - '80:80'
    volumes_from:
      - web
    depends_on:
      - web

  db:
    image: postgres
